# Generated by Django 4.2.3 on 2023-07-17 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_created', models.DateTimeField(auto_now_add=True)),
                ('local_timestamp', models.DateTimeField(null=True)),
                ('event_type', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-local_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('device_hostname', models.CharField(default='?', max_length=15)),
            ],
            options={
                'ordering': ['first_seen'],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logger.event')),
                ('action_id', models.IntegerField(default=0)),
            ],
            bases=('logger.event',),
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logger.event')),
                ('error_string', models.TextField()),
            ],
            bases=('logger.event',),
        ),
        migrations.CreateModel(
            name='GameSessionEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logger.event')),
                ('session_event_type', models.CharField(default='?', max_length=6)),
                ('game_mode', models.IntegerField()),
                ('game_time_elapsed', models.PositiveBigIntegerField()),
                ('player1_score', models.PositiveIntegerField()),
                ('player2_score', models.PositiveIntegerField()),
                ('total_bounces', models.PositiveIntegerField()),
            ],
            bases=('logger.event',),
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.user')),
            ],
            options={
                'ordering': ['-entry_created'],
            },
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_created', models.DateTimeField(auto_now_add=True)),
                ('game_resolution', models.CharField(max_length=9)),
                ('music_toggle', models.BooleanField()),
                ('sound_toggle', models.BooleanField()),
                ('music_volume', models.FloatField()),
                ('sound_volume', models.FloatField()),
                ('gameplay_settings', models.CharField(max_length=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.user')),
            ],
            options={
                'ordering': ['-entry_created'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.user'),
        ),
    ]
