# Generated by Django 4.2.3 on 2023-07-17 09:11

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='local_timestamp',
            field=django_unixdatetimefield.fields.UnixDateTimeField(null=True),
        ),
    ]
