# Generated by Django 4.2.3 on 2023-07-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_alter_event_local_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='local_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
