# Generated by Django 4.2.3 on 2023-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_alter_event_local_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.IntegerField(default=0)),
                ('action_string', models.CharField(max_length=50)),
            ],
        ),
    ]
