# Generated by Django 4.2.3 on 2023-07-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_buttondefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorevent',
            name='error_name',
            field=models.TextField(default='PlaceholderError'),
            preserve_default=False,
        ),
    ]
