# Generated by Django 4.2.3 on 2023-07-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_errorevent_error_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='gameplay_settings',
            field=models.JSONField(null=True),
        ),
    ]
