# Generated by Django 4.2.3 on 2023-07-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_alter_gamesettings_gameplay_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesettings',
            options={'get_latest_by': '-entry_created', 'ordering': ['-entry_created']},
        ),
    ]
