# Generated by Django 4.2.3 on 2023-07-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_alter_gamesettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesessionevent',
            name='serves_missed',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
