# Generated by Django 4.2.3 on 2023-07-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0009_systeminfo_operating_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='processor',
            field=models.CharField(default='Intel Core', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='python_version',
            field=models.CharField(default='3.11.1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='operating_system',
            field=models.CharField(max_length=100),
        ),
    ]
