# Generated by Django 4.2.3 on 2023-07-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0010_systeminfo_processor_systeminfo_python_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systeminfo',
            options={'get_latest_by': '-entry_created', 'ordering': ['-entry_created']},
        ),
    ]
